version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: groundediq-db
    environment:
      POSTGRES_DB: groundediq
      POSTGRES_USER: groundediq
      POSTGRES_PASSWORD: groundediq
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
